image: google/cloud-sdk:latest


variables:
  PROJECT_ID: $GCP_PROJECT_ID
  IMAGE: gcr.io/$GCP_PROJECT_ID/vonome-official-website:latest2

before_script:
  - apt-get update && apt-get install -y wget
  - |
      wget https://github.com/GoogleContainerTools/kaniko/archive/refs/tags/v1.9.1.tar.gz
      tar xzf v1.9.1.tar.gz
      export PATH=$PATH:$PWD/kaniko 
  - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
  - gcloud services enable containerregistry.googleapis.com
  - gcloud --quiet config set project $GCP_PROJECT_ID
  - gcloud --quiet config set container/use_client_certificate False
  - echo "Running on $CI_PROJECT_DIR..."
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

stages:
  - build
  
build:
  stage: build
  # image:
  #   name: gcr.io/kaniko-project/executor:latest
  #   entrypoint: [""]
  script:
    - echo "Start test $IMAGE "
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --no-push
  only:
    - development-2